### PR TITLE
Feature/refactored

### PR DESCRIPTION
**Pull request by eudyptula**
What do you guys say about Android-like onStart/onStop methods on the clients? The security context is created automatically by the ArrowheadClient class and provided to the onStart().

Its behaviour can either be controlled with bootstrap=true/false in the configuration or by calling the set*() methods on ArrowheadClient before calling start().

### CODE REVIEW

**Comment by uzoltan** [comment]
Any change hiding complexity is welcome in a library in my opinion. By the way I think you should be able contribute to the repository directly too, if you want. 

Can you merge this PR for example? Or does Github not allow it?

**Comment by eudyptula** [comment]
I can merge PRs, but had some issues with pushing directly in the beginning - havn't tried since

**Comment by uzoltan** [comment]
I think I added you as collaborator on the 2 main repos, pushing should work too I think.

**Comment by eudyptula** [comment]
Oh, using a 3rd party application requires extra permissions from you - that's why it didn't work! Now it does, at least we got that solved...

**Pull request merged**
